### ISSUE TITLE
d3 is not defined

### ISSUE THREAD

**Issue by dpdonohue** [purplecones/meteor-angular-nvd3#1]
Hi could you add installation instructions?  I ran this

```
meteor add purplecones:angular-nvd3 
```

but I get an error "d3 is not defined"
I tried adding the Meteor d3 package

```
meteor add d3 
```

but still the same error

**Comment by dpdonohue** [comment]
I added 1 line to your package.js file 
`api.use('d3', 'client')`

and now it works for me

```
Package.onUse(function(api) {
  api.versionsFrom('1.1.0.2');
  api.addFiles('nv.d3.js', 'client');
  api.addFiles('nv.d3.css', 'client');
  api.addFiles('angular-nvd3.js', 'client');
  api.use('d3', 'client');
});
```

**Comment by purplecones** [comment]
Fixed thanks. I guess when I used it before I had manually added d3 to my app and didn't catch this.
